language: java
sudo: true
dist: trusty

os:
   - linux
  
jdk:
   - oraclejdk8

install:
   - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

script:
   # object construction
   # - mvn -Dtest=ComputationGraphConstructionTest test -pl shell -e
   # test legitimization
   - mvn -q -Dtest=BooleanFlagGradientTest test -pl shell
   - mvn -q -Dtest=ProjectTestLegitimizationTest test -pl shell
   - mvn -q -Dtest=MethodUtilTest test -pl shell
   #- mvn -Dtest=LayeredCallExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleConstructorsExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleExceptionsExampleTest test -pl EvosuiteTest -e
   # fbranch
   #- mvn -Dtest=ValueRangeExampleTest test -pl EvosuiteTest -e
   # smart mutation
   #- mvn -Dtest=StringArrayExampleTest test -pl EvosuiteTest -e
   # object construction
   #- mvn -Dtest=CascadingCallExampleTest test -pl EvosuiteTest -e
