language: java
sudo: true
# dist: trusty

os:
   - linux
  
jdk:
   - openjdk8

install:
   - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B
   
script:
   # branch enhancement
   - mvn -Dtest=ColtExampleTest test -pl EvosuiteTest -e
   - mvn -Dtest=InevitableConstructorExampleTest test -pl EvosuiteTest -e
   - mvn -Dtest=LayeredCallExampleTest test -pl EvosuiteTest -e
   - mvn -Dtest=MultipleConstructorsExampleTest test -pl EvosuiteTest -e
   - mvn -Dtest=MultipleExceptionsExampleTest test -pl EvosuiteTest -e
   # fbranch
   - mvn -Dtest=FBranchTest#testValueRangeExample test -pl EvosuiteTest -e
   # smart mutation
   - mvn -Dtest=SmartMutationTest#testStringArrayExample test -pl EvosuiteTest -e
   # object construction
   - mvn -Dtest=ObjectConstructionTest#testCascadingCallExample test -pl EvosuiteTest -e
