# This is a basic workflow to help you get started with Actions

name: SmartSeedRuntimeSpecialPointTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, workflow-wip ]
  pull_request:
    branches: [ master, workflow-wip ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Setup JDK8 + JavaFX
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu' # Zulu supports JavaFX, which Evosuite uses.
          java-package: 'jdk+fx'
  
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      # Note: the mvn commands here differ for use on Linux and Windows machines
      # See https://stackoverflow.com/questions/8304110/skip-a-submodule-during-a-maven-build for more details
      # We exclude the 'evosuite-shaded' and 'evosuite-generated' submodules as there are some pre-existing failing tests
      # in those modules. We don't use them anyway (they relate to running Evosuite on itself, a functionality we don't use currently).
      - name: Compile with Maven
        # run: mvn clean test -Dtest=SmartSeedRuntimeTest#testSpecialPoint* -DfailIfNoTests=false -pl '!:evosuite-shaded,!:evosuite-generated'
        run: mvn -DskipTests=true clean source:jar install -Ppackage-jars -T 4
      - name: Run tests with Maven
        run: mvn -DfailIfNoTests=false test -Dtest=ProjectOverallTest#testBasicRules* 
